### ISSUE TITLE
Alphachannel icons look ugly on OS3

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/thebar#4]
Creating toolbar buttons with `BRFLG_ARGB` and `BRFLG_AlphaMask` looks quite ugly on OS3. On OS4 it's looking correctly. Just compare the two images:

![os3](https://cloud.githubusercontent.com/assets/6772528/14938474/fffbce60-0f24-11e6-99a9-f8c24fe69eb5.png)
![os4](https://cloud.githubusercontent.com/assets/6772528/14938476/02c669d4-0f25-11e6-83ea-b53ae3719915.png)

**Comment by tboeckel** [comment]
For me the normal images look wrong already for AmigaOS3. It seems that the alpha channel is not correctly handled by picture.datatype. Instead of returning an image with full 8bit alpha channel it looks like a 1bit alpha channel which treats transparency levels in a "on or off" fashion. How do these images when being displayed with other applications using datatypes.library?

**Comment by tboeckel** [comment]
Argh, sorry, my fault. I didn't read carefully enough. Of course you are referring to embedded raw ARGB image data instead of images loaded by datatypes.library.
Yes, there is definitely a difference between AmigaOS3 and AmigaOS4/MorphOS/AROS regarding alpha channel handling. The reason is that the function WritePixelArrayAlpha is not available on AmigaOS3, unless you have patch like AfAOS running.
I think I will include my custom WritePixelArrayAlpha() function from MUI. This might be slower, but at least it will make correct alpha channel blits possible.
